my_project1\settings
my_project1\settings\init__.py
my_project1\settings\dev.py
my_project1\settings\prod.py
my_project1\mainapp
my_project1\mainapp\__init__.py
my_project1\mainapp\models.py
my_project1\mainapp\views.py
my_project1\mainapp\templates
my_project1\mainapp\templates\mainapp
my_project1\mainapp\templates\mainapp\base.html
my_project1\mainapp\templates\mainapp\index.html
my_project1\authapp
my_project1\authapp\__init__.py
my_project1\authapp\models.py
my_project1\authapp\views.py
my_project1\authapp\templates
my_project1\authapp\templates\authapp
my_project1\authapp\templates\authapp\base.html
my_project1\authapp\templates\authapp\index.html
